name: AWS-EC2 INSTANCE CD

on:
  workflow_run:
    workflow: ["Node.js CI"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      -name: AWS SSH Send-Command
      uses: peterkimzz/aws-ssh-send-command@1.1.1
      with:
        # AWS access key id
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS secret access key
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # Where EC2 instance is
        aws-region: ${{ secrets.AWS_REGION }}
        # AWS EC2 Instance id or ids
        instance-ids: ${{ secrets.AWS_INSTANCE_ID }}
        working-directory: /home/ubuntu
      command: |
        sudo docker-compose stop
        sudo docker-compose rm -f
        sudo docker-compose pull
        sudo docker-compose up -d
        sudo docker image prune -af
      comment: docker-compose.yml file re-pulls newer versions of book-portal images and runs them on the instance.
