import * as Yup from 'yup';
export const validationSchema = Yup.object({
    institution: Yup.string().required('Institution is required').trim().min(5, "must be at least 5 characters long"),
    degree: Yup.string().required('Degree is required').trim().min(5, "must be at least 5 characters long"),
    fieldOfStudy: Yup.string().required('Field of Study is required').trim().min(5, "must be at least 5 characters long"),
    startDate: Yup.date()
        .required('Start Date is required')
        .max(new Date(), 'Start Date cannot be in the future')
});
export const PlanSchema = Yup.object().shape({
    name: Yup.string().transform((_value, originalValue) => originalValue.trim()).required('Name is required'),
    description: Yup.string().transform((_value, originalValue) => originalValue.trim()).required('Description is required'),
    amount: Yup.number().required('Amount is required').positive('Amount must be positive'),
    type: Yup.string().transform((_value, originalValue) => originalValue.trim()).required('Type is required'),
});
export const topSkills: string[] = [
    "JavaScript",
    "Python",
    "Java",
    "HTML",
    "CSS",
    "SQL",
    "Node.js",
    "React",
    "Angular",
    "Vue.js",
    "MongoDB",
    "Express.js",
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "Google Cloud Platform",
    "TensorFlow",
    "PyTorch",
    "Machine Learning",
    "Deep Learning",
    "Artificial Intelligence",
    "Natural Language Processing",
    "Computer Vision",
    "Data Science",
    "Big Data",
    "Hadoop",
    "Spark",
    "Scala",
    "C++",
    "C#",
    "PHP",
    "Ruby",
    "Swift",
    "Objective-C",
    "Kotlin",
    "Flutter",
    "Dart",
    "Unity",
    "Game Development",
    "Cybersecurity",
    "Network Security",
    "Penetration Testing",
    "Blockchain",
    "Cryptocurrency",
    "Ethereum",
    "Smart Contracts",
    "Solidity",
    "Web Development",
    "Frontend Development",
    "Backend Development",
    "Full Stack Development",
    "Responsive Web Design",
    "RESTful APIs",
    "GraphQL",
    "Microservices",
    "DevOps",
    "Continuous Integration",
    "Continuous Deployment",
    "Git",
    "GitHub",
    "GitLab",
    "Jenkins",
    "Agile Methodologies",
    "Scrum",
    "Kanban",
    "Test-Driven Development",
    "Behavior-Driven Development",
    "Selenium",
    "Jira",
    "Confluence",
    "Microsoft Office",
    "Excel",
    "Word",
    "PowerPoint",
    "Google Workspace",
    "G Suite",
    "Microsoft Azure DevOps",
    "Trello",
    "Asana",
    "Slack",
    "Zoom",
    "Microsoft Teams",
    "Communication Skills",
    "Problem Solving",
    "Teamwork",
    "Time Management",
    "Leadership",
    "Creativity",
    "Critical Thinking",
    "Adaptability",
    "Attention to Detail",
    "Organization",
    "Multitasking",
    "Analytical Skills",
    "Presentation Skills",
    "Technical Writing"
];
